sudo: false

language: android

jdk:
  - oraclejdk8

android:
  components:
  - tools
  - platform-tools
  - build-tools-25.2.3
  - android-21
  - sys-img-armeabi-v7a-android-21
  - extra-google-google_play_services
  - extra-android-support
  - extra-android-m2repository
  - extra-google-m2repository

licenses:
  - android-sdk-license-5be876d5

before_script:
  - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script:
  - adb logcat -c
  - ./gradlew connectedCheck

after_success:
  - mkdir -p ./app/build/reports/jacoco/test
  - find . -name report.xml
  - mv ./app/build/reports/coverage/debug/report.xml ./app/build/reports/jacoco/test/jacocoTestReport.xml
  - ./gradlew coveralls
  - bash <(curl -s https://codecov.io/bash)

after_failure:
  - adb logcat -d E

deploy:
  provider: releases
  api-key:
    secure: bkWePIKomwz1uXrhg9Tqj9Ch7DS627K39eFTjNuwtn01kX7pEcxwt8wnSwlAhZP1M/NwTMxHtepc6H5cUKRAWOITuiRA6YVHYgZk6kcET2gsee4eGfWQhSz95/ANmQz1lr2EitHLp+nwAK2cmfiwA+eq3PhViYbrE9IkIx0+38o=
  file: ./app/build/outputs/apk/app-debug.apk
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
